# Generated by Django 3.2.25 on 2024-10-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_video', '0011_alter_videoplayer_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplayer',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_video_videoplayer', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='VideoPlayerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label_new', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('embed_link_new', models.CharField(blank=True, help_text='Use this field to embed videos from external services such as YouTube, Vimeo or others. Leave it blank to upload video files by adding nested "Source" plugins.', max_length=255, verbose_name='Embed link')),
                ('parameters_new', djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, help_text='Parameters are appended to the video link if provided.', verbose_name='Parameters')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djangocms_video.videoplayer')),
                ('poster_new', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Poster')),
            ],
            options={
                'verbose_name': 'video player Translation',
                'db_table': 'djangocms_video_videoplayer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
