# Generated by Django 3.2.25 on 2024-10-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_video', '0012_auto_20241017_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoplayertranslation',
            old_name='embed_link_new',
            new_name='embed_link',
        ),
        migrations.RenameField(
            model_name='videoplayertranslation',
            old_name='label_new',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='videoplayertranslation',
            old_name='parameters_new',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='videoplayertranslation',
            old_name='poster_new',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='embed_link',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='label',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='videoplayer',
            name='poster',
        ),
    ]
